server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: git@github.com:Petlyra/spring-cloud-config.git
          clone-on-start: true
          default-label: master
  security:
    user:
      name: root
      password: password
  application:
    name: config-server
