server:
  port: 8888

spring:
  cloud:
    config:
      server:
        native:
          search-locations: ${searchLocation}
  security:
    user:
      name: root
      password: password
  application:
    name: config-server
